version: "0.1"
services:
  postgresql:
    restart: always
    image: "postgres"
    container_name: "postgres"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=mysecretuser
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ./postgresdata:/var/lib/postgresql/data

  mlflow-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: mlflow-server
    container_name: mlflow-server
    ports:
    - "5000:5000"
    environment:
      - BUCKET=./mlruns
      - USERNAME=mysecretuser
      - PASSWORD=mysecretpassword
      - HOST=postgresql
      - PORT=5432
      - DATABASE=mlflow
    depends_on:
      - postgresql
